package com.jtbdevelopment.e_eye_o.ria.vaadin.components;

import com.google.common.eventbus.EventBus;
import com.jtbdevelopment.e_eye_o.DAO.ReadWriteDAO;
import com.jtbdevelopment.e_eye_o.entities.IdObjectFactory;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;

/**
 * Date: 3/6/13
 * Time: 12:13 AM
 */
public class MainPageComposite extends CustomComponent {

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public MainPageComposite(final ReadWriteDAO readWriteDAO, final IdObjectFactory idObjectFactory, final EventBus eventBus) {
        setSizeFull();

        // the main layout and components will be created here
        HorizontalLayout mainLayout = new HorizontalLayout();
        mainLayout.setSizeFull();

        final SideTabComponent sideTab = new SideTabComponent(eventBus);
        mainLayout.addComponent(sideTab);
        final WorkAreaComponent workArea = new WorkAreaComponent(readWriteDAO, idObjectFactory, eventBus);
        mainLayout.addComponent(workArea);
        mainLayout.setExpandRatio(workArea, 1);
        setCompositionRoot(mainLayout);
    }

}
