package com.jtbdevelopment.e_eye_o.ria.vaadin.components;

import com.jtbdevelopment.e_eye_o.entities.AppUser;
import com.vaadin.server.ExternalResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.*;
import com.vaadin.ui.themes.Runo;

/**
 * Date: 3/5/13
 * Time: 11:23 PM
 */
public class TitleBarComposite extends CustomComponent {

    private HorizontalLayout mainLayout;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public TitleBarComposite(final AppUser appUser) {
        buildMainLayout(appUser);
        setCompositionRoot(mainLayout);
    }

    private void buildMainLayout(final AppUser appUser) {
        setWidth(100, Unit.PERCENTAGE);
        setHeight(null);
        // the main layout and components will be created here
        mainLayout = new HorizontalLayout();
        mainLayout.setSizeFull();

        Label welcomeLabel = new Label("Welcome " + appUser.getViewableDescription());
        welcomeLabel.setWidth(null);
        mainLayout.addComponent(welcomeLabel);
        mainLayout.setComponentAlignment(welcomeLabel, Alignment.MIDDLE_LEFT);
        mainLayout.setExpandRatio(welcomeLabel, 0.2f);

        Label appLabel = new Label("E-EYE-O");
        appLabel.setWidth(null);
        mainLayout.addComponent(appLabel);
        mainLayout.setComponentAlignment(appLabel, Alignment.MIDDLE_CENTER);
        mainLayout.setExpandRatio(appLabel, 0.5f);

        Button settingsButton = new Button("Settings");
        settingsButton.setStyleName(Runo.BUTTON_LINK);
        settingsButton.setIcon(new ThemeResource("../runo/icons/16/settings.png"));
        mainLayout.addComponent(settingsButton);
        mainLayout.setComponentAlignment(settingsButton, Alignment.MIDDLE_CENTER);
        mainLayout.setExpandRatio(settingsButton, 0.2f);

        Link logout = new Link("Logout", new ExternalResource("/j_spring_security_logout"));
        mainLayout.addComponent(logout);
        mainLayout.setComponentAlignment(logout, Alignment.MIDDLE_RIGHT);

    }

}
