package com.jtbdevelopment.e_eye_o.ria.vaadin.components;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import com.jtbdevelopment.e_eye_o.DAO.ReadOnlyDAO;
import com.jtbdevelopment.e_eye_o.entities.AppUser;
import com.jtbdevelopment.e_eye_o.entities.Student;
import com.jtbdevelopment.e_eye_o.entities.utilities.IdObjectFactory;
import com.jtbdevelopment.e_eye_o.ria.vaadin.events.TreeSelectionChanged;
import com.jtbdevelopment.e_eye_o.ria.vaadin.widgets.IdObjectTreeView;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Reindeer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Date: 3/6/13
 * Time: 12:13 AM
 */
@Scope("prototype")
@Component
public class WorkAreaComposite extends CustomComponent {

    @AutoGenerated
    private HorizontalSplitPanel mainLayout;

    @Autowired
    private ReadOnlyDAO readOnlyDAO;

    @Autowired
    private IdObjectFactory idObjectFactory;

    private final EventBus eventBus = new EventBus();

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public WorkAreaComposite() {
        eventBus.register(this);
    }

    @Override
    public void attach() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        super.attach();
    }

    @AutoGenerated
    private void buildMainLayout() {
        setSizeFull();
        // the main layout and components will be created here
        mainLayout = new HorizontalSplitPanel();
        mainLayout.setSplitPosition(15);
        mainLayout.setSizeFull();
        mainLayout.setStyleName(Reindeer.SPLITPANEL_SMALL);

        VerticalLayout trees = new VerticalLayout();
        mainLayout.setFirstComponent(trees);

        AppUser appUser =  getSession().getAttribute(AppUser.class);
        trees.addComponent(new IdObjectTreeView(appUser, readOnlyDAO, eventBus, "Active", false));
        trees.addComponent(new IdObjectTreeView(appUser, readOnlyDAO, eventBus, "Archived", true));

    }

    @Subscribe
    public void treeSelectionChange(final TreeSelectionChanged treeSelectionChanged) {
        if(Student.class.isAssignableFrom(treeSelectionChanged.getEntityType())) {
            Student s = (Student) readOnlyDAO.get(treeSelectionChanged.getEntityType(), treeSelectionChanged.getEntityId());
            if (s == null) {
                s = idObjectFactory.newStudent(getSession().getAttribute(AppUser.class));
            }
            mainLayout.setSecondComponent(new StudentForm(s));
        } else {
            Label eventLabel=new Label("Something");
            eventLabel.setValue(treeSelectionChanged.getEntityId());
            mainLayout.setSecondComponent(eventLabel);
        }
    }

}
