package com.jtbdevelopment.e_eye_o.ria.vaadin.components;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import com.jtbdevelopment.e_eye_o.ria.vaadin.events.IdObjectRelatedSideTabClicked;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.themes.Runo;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.annotation.Scope;

/**
 * Date: 3/10/13
 * Time: 4:19 PM
 */
@org.springframework.stereotype.Component
@Scope("prototype")
public class WorkAreaComponent extends CustomComponent implements ApplicationContextAware {

    private ApplicationContext applicationContext;

    private final Panel mainLayout;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    @Autowired
    public WorkAreaComponent(final EventBus eventBus) {
        eventBus.register(this);
        mainLayout = new Panel();
//        mainLayout.setMargin(new MarginInfo(false, true, true, true));
//        mainLayout.setSpacing(true);
        mainLayout.addStyleName(Runo.PANEL_LIGHT);
        mainLayout.setSizeFull();
        setSizeFull();
        setCompositionRoot(mainLayout);
    }

    @Subscribe
    @SuppressWarnings("unused")
    public void changeDataArea(final IdObjectRelatedSideTabClicked event) {
        Notification.show("Switching to " + event.getEntityType().getCaption());
        mainLayout.setContent(null);
//        for (final Object childComponent : mainLayout) {
//            mainLayout.removeComponent((Component) childComponent);
        //       }
        switch (event.getEntityType()) {
            case Students:
//                mainLayout.addComponent(applicationContext.getBean(StudentsWorkArea.class));
                mainLayout.setContent(applicationContext.getBean(StudentsWorkArea.class));
                break;
            default:
                //  TODO - log or notify
        }
    }

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }
}
